import type { Metadata } from "next";
import "../app/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//add metatagfs

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      {/* add sidebar */}
      {/* add topbar in the dashboard routes */}
      <body>{children}</body>
      {/* add footer */}
    </html>
  );
}
