import type { Metadata } from "next";
import "../app/styles/globals.css";

import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "ProporsalAI",
  description: "Generated by create next app",
};

//add metatags and keywords

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      {/* add sidebar */}
      {/* add topbar in the dashboard routes */}
      <body>{children}</body>
      {/* add footer */}
    </html>
  );
}
